Repository aneoconsulting/ArmoniK.Core, pull requests merged in 2022-11, with the labels that each got.

#172 Gui endpoint authentication support
  Adaptors/MongoDB/src/AuthenticationTable.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/AuthMongoUtils.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/PipelineIntermediates.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs
  Adaptors/MongoDB/tests/AuthenticationTableTest.cs
  Adaptors/MongoDB/tests/BsonSerializerTest.cs
  Common/src/Auth/Authentication/Authenticator.cs
  Common/src/Auth/Authentication/UserIdentity.cs
  Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
  Common/src/Auth/Authorization/GeneralService.cs
  Common/src/Auth/Authorization/Permissions.cs
  Common/src/Auth/Authorization/Permissions/Permission.cs
  Common/src/Auth/Authorization/Permissions/PermissionScope.cs
  Common/src/Auth/Authorization/Permissions/ServicesPermissions.cs
  Common/src/Auth/Authorization/RequiresPermissionAttribute.cs
  Common/src/gRPC/Services/GrpcResultsService.cs
  Common/src/gRPC/Services/GrpcSessionsService.cs
  Common/src/gRPC/Services/GrpcSubmitterService.cs
  Common/src/gRPC/Services/GrpcTasksService.cs
  Common/tests/Auth/AuthenticationIntegrationTest.cs
  Common/tests/Auth/AuthenticationTableTestBase.cs
  Common/tests/Auth/MockIdentity.cs
  Common/tests/Auth/PermissionTest.cs
  Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
  Common/tests/Helpers/SimpleResultTable.cs
  Common/tests/Helpers/SimpleSessionTable.cs
  Common/tests/Helpers/SimpleTaskTable.cs
Labels: enhancement

#190 Fix versionning in pipeline
  .github/workflows/build.yml
Labels: bug

#185 Added authentication guide link
  Documentation/articles/authentication.md
Labels: documentation

#193 Remove input payload after completed task in Redis
  Adaptors/Redis/src/ObjectStorage.cs
  Common/src/gRPC/Services/Submitter.cs
  Common/tests/ObjectStorageTestBase.cs
Labels: enhancement
