Repository aneoconsulting/ArmoniK.Core, pull requests merged in 2022-10, with the labels that each got.

#157 Rework Amqp adapter to expose its health check and use health check to check service statuses after stopping them
  .github/workflows/build.yml
  Adaptors/Amqp/src/ConnectionAmqp.cs
  Adaptors/Amqp/src/ConnectionProvider.cs
  Adaptors/Amqp/src/IConnectionAmqp.cs
  Adaptors/Amqp/src/IPullSessionAmqp.cs
  Adaptors/Amqp/src/ISessionAmqp.cs
  Adaptors/Amqp/src/PullQueueStorage.cs
  Adaptors/Amqp/src/PullSessionAmqp.cs
  Adaptors/Amqp/src/PullSessionProvider.cs
  Adaptors/Amqp/src/PushQueueStorage.cs
  Adaptors/Amqp/src/QueueStorage.cs
  Adaptors/Amqp/src/ServiceCollectionExt.cs
  Adaptors/Amqp/src/SessionAmqp.cs
  Adaptors/Amqp/tests/QueueStorageTests.cs
  Common/src/Pollster/Pollster.cs
  Compute/PollingAgent/src/Program.cs
  Control/Submitter/src/Program.cs
  tools/test_healthcheck.sh
Labels: bug

#156 Have a maximum allowed number of errors before crashing
  Common/src/Injection/Options/Pollster.cs
  Common/src/Injection/Options/Submitter.cs
  Common/src/Pollster/Pollster.cs
  Common/src/Pollster/TaskHandler.cs
  Common/src/gRPC/ExceptionInterceptor.cs
  Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
  Common/tests/Pollster/PollsterTest.cs
  Common/tests/Pollster/TaskHandlerTest.cs
  Common/tests/Submitter/ExceptionInterceptorTests.cs
  Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
  Control/Submitter/src/Program.cs
  docker-compose/docker-compose.yml
  tools/test_healthcheck.sh
Labels: bug

#164 Better error management in TaskHandler
  Common/src/Pollster/TaskHandler.cs
  Common/tests/Pollster/TaskHandlerTest.cs
Labels: bug

#168 Modified pipeline to merge arm images
  .github/workflows/build.yml
  .github/workflows/make-release.yml
Labels: enhancement

#167 Added more documentation for auth
  Adaptors/MongoDB/src/AuthenticationTable.cs
  Adaptors/MongoDB/src/ServiceCollectionExt.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/AuthDataModelMapping.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/PipelineIntermediates.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/RoleDataModelMapping.cs
  Adaptors/MongoDB/src/Table/DataModel/Auth/UserDataModelMapping.cs
  Common/src/Auth/Authentication/AuthenticationCache.cs
  Common/src/Auth/Authentication/Authenticator.cs
  Common/src/Auth/Authentication/IAuthenticationTable.cs
  Common/src/Auth/Authentication/UserAuthenticationResult.cs
  Common/src/Auth/Authentication/UserIdentity.cs
  Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
  Common/src/Auth/Authorization/Permissions.cs
  Common/src/Auth/Authorization/RequiresPermissionAttribute.cs
Labels: documentation
