Repository aneoconsulting/ArmoniK.Core, pull requests merged in 2023-02, with the labels that each got.

#233 chore: Remove pass-through methods from ISubmitter interface
  Common/src/Pollster/TaskHandler.cs
  Common/src/Storage/TaskStatusCount.cs
  Common/src/gRPC/Services/GrpcSubmitterService.cs
  Common/src/gRPC/Services/ISubmitter.cs
  Common/src/gRPC/Services/Submitter.cs
  Common/tests/Helpers/GrpcSubmitterServiceHelper.cs
  Common/tests/Helpers/SimpleSubmitter.cs
  Common/tests/Submitter/GrpcSubmitterServiceTests.cs
  Common/tests/Submitter/IntegrationGrpcSubmitterServiceTest.cs
  Common/tests/Submitter/SubmitterTests.cs
Labels: enhancement

#255 fix: when redis adapter fails there is no retry
  Adaptors/Redis/src/ObjectStorage.cs
  Adaptors/Redis/src/ObjectStorageFactory.cs
  Adaptors/Redis/src/Options/Redis.cs
  Adaptors/Redis/tests/ObjectStorageTests.cs
Labels: bug

#258 feat: add logs of partion metrics call
  .github/workflows/build.yml
Labels: enhancement

#257 fix: too many queries on metrics exporter on mongodb
  Common/src/Utils/ExecutionSingleizer.cs
  Common/tests/Utils/ExecutionSingleizerTest.cs
  Control/Metrics/src/ArmoniKMeter.cs
  Control/PartitionMetrics/src/ArmoniKMeter.cs
Labels: bug

#264 docs: add new template
  .docs/.gitignore
  .docs/.npmrc
  .docs/README.md
  .docs/app.config.ts
  .docs/components/content/Mermaid.vue
  .docs/content/0.index.md
  .docs/content/1.concepts/1.tasks.md
  .docs/content/1.concepts/2.authentication.md
  .docs/content/1.concepts/_dir.yml
  .docs/nuxt.config.ts
  .docs/package.json
  .docs/pnpm-lock.yaml
  .docs/public/.nojekyll
  .docs/public/favicon.ico
  .docs/tokens.config.ts
  .docs/tsconfig.json
  .github/workflows/build_documentations.yml
  .github/workflows/deploy-docs.yml
  Documentation/.gitignore
  Documentation/api/.gitignore
  Documentation/api/index.md
  Documentation/articles/intro.md
  Documentation/articles/toc.yml
  Documentation/docfx.json
  Documentation/index.md
  Documentation/templates/armonik/logo.svg
  Documentation/templates/armonik/styles/main.css
  Documentation/templates/mermaid/partials/scripts.tmpl.partial
  Documentation/toc.yml
Labels: documentation
